# Generated by Django 5.2.6 on 2025-09-10 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Company name as entered by users')),
                ('slug', models.SlugField(help_text='URL-friendly version of company name', max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, help_text='Industry sector (optional)', max_length=100, null=True)),
                ('is_suspect', models.BooleanField(default=False, help_text='True if company is flagged for suspicious activity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'indexes': [models.Index(fields=['slug'], name='companies_slug_e0676c_idx'), models.Index(fields=['name'], name='companies_name_c7a1b3_idx'), models.Index(fields=['created_at'], name='companies_created_c84a3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fairness', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Fairness rating (1-5)')),
                ('work_life_balance', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Work-life balance rating (1-5)')),
                ('management_toxicity', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Management toxicity rating (1-5, higher = more toxic)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='companies.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Rating',
                'verbose_name_plural': 'Company Ratings',
                'db_table': 'company_ratings',
                'indexes': [models.Index(fields=['company', 'created_at'], name='company_rat_company_75dd56_idx')],
                'unique_together': {('company', 'user')},
            },
        ),
    ]
