# Generated by Django 5.2.6 on 2025-09-10 07:31

import django.db.models.deletion
import django.utils.timezone
import posts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional post title', max_length=200, null=True)),
                ('body', models.TextField(help_text='Main post content', validators=[posts.models.validate_no_pii])),
                ('media_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs (max 5)')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags (e.g., ['#salary', '#harassment'])")),
                ('score', models.IntegerField(default=0, help_text='Calculated score based on votes')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by moderators')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-deleted by user or moderator')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the post was deleted', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company being discussed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='companies.company')),
                ('user', models.ForeignKey(help_text='Author (nullable for anonymity)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='Comment content', validators=[posts.models.validate_no_pii])),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by moderators')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], help_text='1 for upvote, -1 for downvote')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['company', '-created_at'], name='posts_company_29c7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-score'], name='posts_score_3c896a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden', 'is_deleted'], name='posts_is_hidd_55d5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comments_post_id_8fd787_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_parent__9f8798_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['post', 'vote'], name='votes_post_id_572b4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'post')},
        ),
    ]
