# Generated by Django 5.2.6 on 2025-09-10 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('pii', 'Contains Personal Information'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('spam', 'Spam or Low Quality'), ('threats', 'Threats or Violence'), ('doxxing', 'Doxxing/Personal Information'), ('illegal', 'Illegal Content'), ('other', 'Other Violation')], help_text='Reason for the report', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details from reporter')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Sanitized metadata (no PII)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on resolution')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('handled_by', models.ForeignKey(blank=True, help_text='Admin who handled this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter_user', models.ForeignKey(blank=True, help_text='User who submitted the report (nullable for anonymity)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('hide_post', 'Hide Post'), ('unhide_post', 'Unhide Post'), ('delete_post', 'Delete Post'), ('hide_comment', 'Hide Comment'), ('unhide_comment', 'Unhide Comment'), ('delete_comment', 'Delete Comment'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report')], max_length=20)),
                ('target_object_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata (no PII)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.report')),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='AuditLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(help_text="Type of referenced object (e.g., 'post', 'user')", max_length=50)),
                ('reference_id', models.UUIDField(help_text='ID of the referenced object')),
                ('encrypted_payload', models.BinaryField(help_text='Encrypted JSON payload (requires KMS to decrypt)')),
                ('requires_legal_hold', models.BooleanField(default=False, help_text='True if legal hold prevents deletion')),
                ('purpose', models.CharField(help_text='Purpose of this audit link', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this audit link expires (if applicable)', null=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this audit link', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Link',
                'verbose_name_plural': 'Audit Links',
                'db_table': 'audit_links',
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='audit_links_referen_d21dcd_idx'), models.Index(fields=['created_at'], name='audit_links_created_0b36e8_idx'), models.Index(fields=['expires_at'], name='audit_links_expires_9c0e26_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='reports_status_d7deb7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='reports_content_0cd725_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason'], name='reports_reason_cd75fc_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['-created_at'], name='admin_audit_created_5c232f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_user', '-created_at'], name='admin_audit_admin_u_1f122d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action'], name='admin_audit_action_d6f52c_idx'),
        ),
    ]
